config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  post 'events/:id/edit', to: 'events#edit'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_and_belongs_to_many :users
     belongs_to :creator, class_name: 'User'
     	validates :price, numericality: { only_integer: true }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :sanitize_devise_params, if: :devise_controller?

	def sanitize_devise_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])		
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @users = User.all
    if user_signed_in?
      @attendees = current_user.events
    else
      @attendees
    end
  end

	def new
    @event =Event.new
    flash[:success] = "vous avez bien crée un event"
  end

  def index
    @events = Event.all
    @users = User.all
  end

  def create
    Event.create(:description => params[:event][:description], :date => params[:event][:date], :place => params[:event][:place], :price => params[:event][:price], :creator_id => current_user.id)
    @event = Event.last
        flash[:success] = "vous avez bien crée un event"

  end

  def show
    @event = Event.find(params[:id])
    @user = User.all
    @b = @event.users
        flash[:success] = "vous avez bien crée un event"


  end
  def showid
    @event = Event.find(params[:id])
    @user = User.all
    @b = @event.users
  end



  def edit
    a = Event.find(params[:id])
    b = User.find(current_user.id)

    if a.price == 0
     a.users << b
     redirect_to root_path

    end
    @amount = a.price * 100
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
      )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount ,
      :description => '#{amount}',
      :currency    => 'eur'
      )
    a.users << b
    flash[:success] = 'Votre paiement a bien été pris en compte'
    redirect_to root_path


  rescue Stripe::CardError => e
    flash[:error] = e.message


  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@events = Event.all
  	@users = User.all
  	if user_signed_in?
    	@attendees = current_user.events
	else
		@attendees
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/create.html.erb
  <div><%= flash[:error] %></div>
  <div><%= flash[:succes] %></div>

<p>L'événement  <%= @event.description %> a bien été crée</p>
<p>Il aura lieu le : <%= @event.date %> à <%= @event.place %> Souhaites tu y participer.</p>

app/views/events/index.html.erb
<% unless user_signed_in? %>
<section>
	<div class="container">
		<h1>Merci de te connecter pour avoir accés aux events</h1>
		<%= form_for(:user, :url => session_path(:user)) do |f| %>
		<div class="form-group">
			<%= f.label :email %>:
			<%= f.text_field :email, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<%= f.label :password %>:
			<%= f.password_field :password, class: "form-control" %>
		</div>
		<div class="form-check">
			<%= f.check_box :remember_me, class: "form-check-input" %>
			<%= f.label :remember_me, class: "form-check-label" %>
		</div>
		<%= f.submit 'Sign in', class: "btn btn-primary btn-connexion" %>
		<%= link_to "Forgot your password?", new_password_path(:user) %>

		<% end %>
	</div>
</section>
<% else %>
<section>
	<div class="container">
		<h1>Liste des événements</h1>
		<div class="table-responsive"> 
			<table class="table table-hover table-dark-ligth">
				<thead>
					<tr>
						<th scope="col"><span class="fi-media-play"></span>#</th>
						<th scope="col">Event :</th>
						<th scope="col">Date :</th>
						<th scope="col">Place :</th>
						<th scope="col">Prix :</th>
						<th scope="col">Crée par :</th>
						<th scope="col">Nb de participants :</th>
						<th scope="col">Voir l'event :</th>


					</tr>
				</thead>
				<% @events.order(:date).each do |t| %>
				<tbody>
					<th> <%= t.id %></th>
					<th> <%= t.description %></th>								
					<th> <%= t.date.strftime('%a %d %b %Y')  %></th>
					<th> <%= t.place %></th>
					<th> <%= t.price %></th>
					<th> <%= @users.find(t.creator_id).username %></th>

					<th> <%= t.users.count %></th>
					<th><%= link_to 'show', event_path(t.id), class: 'btn btn-primary' %> </th>

				</tbody>
				<% end %>
			</table>
		</div> 
	</div>
</section>
<% end %>

app/views/events/new.html.erb
<section>
	<div class="container">
		<h1>Créer un événement</h1>
		<%= form_for @event, url: {action: "create"} do |f| %>
		<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description, class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.label :date %>
		<%= f.date_field :date, class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.label :place %>
		<%= f.text_field :place, class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.label :price %>
		<%= f.number_field :price, in: 1...10000, class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.submit "Créer", class: "btn btn-primary" %>
		</div>
		<% end %>
	</div>
</section>

app/views/events/show.html.erb
<section>
	<div class="container">
		<h1>Information</h1>
		<div class="table-responsive"> 
			<table class="table table-hover table-dark-ligth">
				<thead>
					<tr>
						<th scope="col"><span class="fi-media-play"></span>#</th>
						<th scope="col">Evénement :</th>
						<th scope="col">Date :</th>
						<th scope="col">Lieu :</th>
						<th scope="col">Créateur :</th>
						<th scope="col">Participer :</th>
					</tr>
				</thead>
				<tbody>
					<th > <%= @event.id %></th>
					<th > <%= @event.description %></th>
					<th > <%= @event.date %></th>
					<th > <%= @event.place %></th>
					<th> <%= @user.find(@event.creator_id).username %></th>
					<% if Time.now > @event.date  %>
					<th><%= 'Vous ne pouvez pas participer à un évent passé' %></th>
					<%elsif @event.price == 0 %>
					<th><%= link_to 'Participer', edit_event_path, class: 'btn btn-primary' %> </th>


					<% else %> 

					<th><%= form_tag edit_event_path do %>
						<article> <% if flash[:error].present? %>
							<div id="error_explanation">
								<p><%= flash[:error] %></p>
							</div>
							<% end %>
							<% if @event.users.include? current_user%>
							<div id="error_explanation">
								<p><%= 'Vous participez déja a cet évent' %></p>
							</div>
							<% else %>
							<label class="amount">
								<span>Prix: <%= @event.price %> €</span>
							</label>
						</article>				

						<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
						data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
						data-description="<%= @event.description %>"
						data-amount="<%= @event.price * 100 %>"
						data-locale="auto"></script>
						<% end %>
						<% end %>
						<% end %>
					</th>
				</tbody>
			</table>
		</div>
		<h2>Liste</h2>
		<div class="table-responsive"> 
			<table class="table table-hover table-dark-ligth">
				<thead>
					<tr>
						<th scope="col"><span class="fi-media-play"></span>#</th>
						<th scope="col">Participants :</th>
					</tr>
				</thead>
				<tbody>
					<% @b.each do |u| %>
					<tr>
						<th > <%= u.id %></th>
						<th > <%= u.username %></th>
					</tr>
					<%end%>
				</tbody>
			</table>
		</div>
	</div>
</section>

app/views/home/index.html.erb
<% unless user_signed_in? %>
<section>
	<div class="container">
		<h1>Connexion</h1>
		<%= form_for(:user, :url => session_path(:user)) do |f| %>
		<div class="form-group">
			<%= f.label :email %>:
			<%= f.text_field :email, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<%= f.label :password %>:
			<%= f.password_field :password, class: "form-control" %>
		</div>
		<div class="form-check">
			<%= f.check_box :remember_me, class: "form-check-input" %>
			<%= f.label :remember_me, class: "form-check-label" %>
		</div>
		<%= f.submit 'Sign in', class: "btn btn-primary btn-connexion" %>
		<%= link_to "Forgot your password?", new_password_path(:user) %>

		<% end %>
	</div>
</section>
<% else %>
<section>
	<div class="container">
		<h1>Liste des événements</h1>

		<div class="table-responsive"> 
			<table class="table table-hover table-dark-ligth">
				<thead>
					<tr>
						<th scope="col"><span class="fi-media-play"></span>#</th>
						<th scope="col">Event :</th>
						<th scope="col">Date :</th>
						<th scope="col">Place :</th>
						<th scope="col">Prix :</th>
						<th scope="col">Crée par :</th>
						<th scope="col">Nb de participants :</th>
						<th scope="col">Voir l'event :</th>


					</tr>
				</thead>
				<% @events.order(:date).each do |t| %>
				<tbody>
					<th> <%= t.id %></th>
					<th> <%= t.description %></th>								
					<th> <%= t.date.strftime('%a %d %b %Y')  %></th>
					<th> <%= t.place %></th>
					<th> <%= t.price %></th>
					<th> <%= @users.find(t.creator_id).username %></th>

					<th> <%= t.users.count %></th>
					<th><%= link_to 'show', event_path(t.id), class: 'btn btn-primary' %> </th>

				</tbody>
				<% end %>
			</table>
		</div> 
	</section>
	<section>
		<div class="container">
			<h1>Liste des événements auquel tu participes</h1>

			<div class="table-responsive">
				<table class="table table-hover table-dark-ligth">
					<thead>
						<tr>
							<th scope="col"><span class="fi-media-play"></span>#</th>
							<th scope="col">Event :</th>
							<th scope="col">Date :</th>
							<th scope="col">Place :</th>
							<th scope="col">Prix :</th>
							<th scope="col">Crée par :</th>
							<th scope="col">NB de participants :</th>
							<th scope="col">Voir l'event :</th>


						</tr>
					</thead>
					<% @attendees.order(:date).each do |t| %>
					<tbody>
						<th> <%= t.id %></th>
						<th> <%= t.description %></th>								
						<th> <%= t.date %></th>
						<th> <%= t.place %></th>
						<th> <%= t.price %></th>
						<th> <%= @users.find(t.creator_id).username %></th>
						<th> <%= t.users.count %></th>
						<th><%= link_to 'show', event_path(t.id), class: 'btn btn-primary' %> </th>

					</tbody>
					<% end %>
				</table>
			</div>
		</section>
		<section>
			<div class="container">
				<div class="table-responsive">
					<table class="table table-hover table-dark-ligth">
						<%=link_to 'Créer un nouvel event', new_event_path , class: 'btn btn-primary btn-lg' %> 
					</table>
				</div>
			</div>
		</section>

		<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventBriteDevise</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.1/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-WuViQmTamrPyvMFZjf8te7HpKtdxuzV/HX1yG26a0d8yieIBr+beDf1ME99iX1cM" crossorigin="anonymous">

</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">

        
        <a class="navbar-brand" href="/">Accueil</a>

        <a class="navbar-brand" href="/events">Les Events</a>
        <ul class="navbar-nav navbar-right">

          <% if user_signed_in? %>
          <li>
            <%= link_to 'Mon profil', edit_user_registration_path, class: 'nav-link' %>
          </li> 
          <li>
            <%= link_to 'Deconnecte toi', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Connexion', new_user_session_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to 'Créer un compte', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    

  </header>
  <div><%= flash[:error] %></div>
  <div><%= flash[:succes] %></div>
  <%= yield %>
  <footer>
    <div class="container">
      <p>Made by Guillaume & Pierre</p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>